Solarized Colorscheme for Netbeans
==================================
Marco Herrn <marco@mherrn.de>
2018-03-17
:notoc:
:homepage: https://github.com/hupfdule/solarized-netbeans-colorscheme
:solarized-homepage: http://ethanschoonover.com/solarized
:fenti-solarized-colorscheme-homepage: https://github.com/fentie/netbeans-colors-solarized
:download-page: https://github.com/hupfdule/solarized-netbeans-colorscheme/releases
:source-highlighter: prettify
:version: 1.0.0-SNAPSHOT

Solarized Colorscheme for Netbeans

A Colorscheme for Netbeans that is inspired by the
{solarized-homepage}[Solarized Colorscheme for Vim].

This Colorscheme is derived from the
{fenti-solarized-colorscheme-homepage}[Solarized Colorscheme of Brian
Fenton].


Installation
------------

1. Get the current release from the {download-page}[Download page].
2. In Netbeans, select "Tools" / "Options" and press the "Import…" button at the 
   lower left of the window.
3. Navigate to the downloaded zip-file and click "OK".
4. Restart the IDE

Variants
--------

This colorscheme currently only supports the light version. It is not an
exact copy of the original Solarized colorscheme, but uses some
derivations.

License
-------

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
